base_name: test_run
batch_size: 2
checkpoint_directory: checkpoints
checkpoint_interval: 1
content_weight: 0.0
crop_size: 256
display_size: 16
fine_tuning_iterations: 1
image_display_iter: 1
image_save_iter: 1
lap_weight: 1
log_interval: 1
logs_directory: logs
lr: 0.0001
lr_decay: 5.0e-05
mode: photorealistic
model_save_interval: 1
new_size: 512
rec_weight: 10
resume: false
resume_iter: -1
style_weight: 1.0
temporal_weight: 0
train_content: data/train_content
train_style: data/train_style
training_iterations: 10
use_lap: true
vgg_ckpoint: checkpoints/vgg_normalised.pth
win_rad: 1
