model:
  type: cap_vstnet
  checkpoint: checkpoints/photo_image.pt

training:
  epochs: 50
  batch_size: 16
  learning_rate: 0.001
  content_weight: 1.0
  style_weight: 1.0
  laplacian_weight: 1.0

data:
  content_dir: data/content/
  style_dir: data/style/
  image_size: 256

augmentation:
  use_segmentation: false
  segmentation_model: segformer
  auto_segmentation: false
